config/routes.rb
Centimos::Application.routes.draw do
  root to: 'static_pages#home'
  
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "1 centimo"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">1 céntimo</a> por Daniel López
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "1 céntimo", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Ayuda", help_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Ayuda') %>
<div class="header">
<h1>Ayuda</h1>
<p>Cupcake ipsum dolor sit amet. Gingerbread muffin cookie. Jelly liquorice chocolate bar. Toffee pie sesame snaps lemon drops pudding fruitcake. Powder candy jelly beans cupcake dragée pastry sweet roll tootsie roll. Caramels oat cake cotton candy chocolate cake halvah. Faworki chocolate cake lollipop toffee. Topping caramels cotton candy liquorice chocolate apple pie. Donut halvah carrot cake applicake croissant toffee gummi bears jujubes sweet roll. Macaroon carrot cake tiramisu powder tart sugar plum wypas icing gummi bears. Toffee sweet chupa chups jelly. Sweet cheesecake sugar plum powder gummi bears cupcake. Dragée toffee sugar plum sweet roll toffee jelly beans jujubes donut jelly beans. Brownie liquorice topping liquorice cake pie muffin soufflé sesame snaps.</p>
</div>

app/views/static_pages/home.html.erb
<div class="hero-unit center">
	<h1>1 céntimo</h1>
	<h2>¿Cuánto mediría esta cantidad de dinero en monedas de 1 céntimo?</h2>
	
	<form class="form-horizontal">
	  <fieldset>
	    <div class="control-group">
	        <input type="number" class="input-xlarge" id="input01" value="0">
			<button type="submit" class="btn">Calcular!</button>
	    </div>
	  </fieldset>
	</form>
</div>